### ISSUE TITLE
Sell your code

### ISSUE THREAD

**Issue by wilsden** [ZquaRe/Tiktok-Downloader#3]
https://codecanyon.net/item/tiktok-video-downloader-with-ajax/26284627

**Comment by wilsden** [comment]
File a complaint!

**Comment by hardikforall** [comment]
Hello @ZquaRe  

The above user has posted a comment on my script page saying that I am selling someone else's labor. and also posted a GitHub link to your repository stating that the script is copied from here.

I have checked both the code and there is no single line in the code similar to your code. 

Also, He is saying design is similar to that code in below replies but the design is not at all similar to your design. in fact, the current design of my TikTok downloader script is the same as my Instagram video downloader script Which I have uploaded two years ago. 

https://codecanyon.net/item/instagram-videoimage-downloader-with-ajax-multi-content/20997700 

@wilsden I request you to remove this comment thread as it is not true
